function [params,logL,predicted,w,d,C] = fit_bim_bins_recog(nR_S1,nR_S2)
% [params,logL,predicted,w,d,C] = fit_bim_bins_recog(nR_S1,nR_S2)
%
% Fit BIM to data from recognition tasks with confidence ratings on a
% discrete scale.
% 
% INPUTS
%
% * nR_S1, nR_S2
% These are vectors containing the number of trials in each response
% category, conditional on presentation of S1 and S2. S1 responses are
% always listed first, followed by S2 responses.
%
% e.g. If nR_S1 = [100 50 20 10 5 1], then when S1 stimulus was
% presented, the subject had the following response counts:
% responded S1, confidence rating=3 : 100 trials
% responded S1, confidence rating=2 : 50 trials
% responded S1, confidence rating=1 : 20 trials
% responded S2, confidence rating=1 : 10 trials
% responded S2, confidence rating=2 : 5 trials
% responded S2, confidence rating=3 : 1 trial
%
% And if nR_S2 = [2 6 9 18 40 110], then when S2 stimulus was
% presented, the subject had the following response counts:
% responded S1, confidence rating=3 : 2 trials
% responded S1, confidence rating=2 : 6 trials
% responded S1, confidence rating=1 : 9 trials
% responded S2, confidence rating=1 : 18 trials
% responded S2, confidence rating=2 : 40 trials
% responded S2, confidence rating=3 : 110 trials
%
% PLEASE NOTE: BIM requires confidence ratings to be on a scale with no
% less than 3 points.
%
% nR_S1 and nR_S2 can be generated by the function trials2counts from the
% code for the meta-d' model (Maniscalco & Lau, 2012). The cells with zero
% value in nR_S1 or nR_S2 do not affect the fit of BIM, and thus we
% recommend setting padCells = 0 when using the function trials2counts.
%
% OUTPUTS
%
% * params
% A vector containing fitted value of the parameters in BIM (from left to
% right: Pexp, Mconf for S1 stimulus with S1 response, Mconf for S1
% stimulus with S2 response, Mconf for S2 stimulus with S1 response, Mconf
% for S2 stimulus with S2 response, rho).
%
% * logL
% Log likelihood of the data fit.
%
% * predicted
% A struct containing two fields: "S1" and "S2".
% predicted.S1 is the model prediction about the proportion of trials in
% each response category with S1 stimulus. predicted.S2 is the model
% prediction about the proportion of trials in each response category with
% S2 stimulus.
%
% e.g. If predicted.S1 = [0.55 0.2 0.15 0.05 0.03 0.02], then when S1
% stimulus was presented, the model prediction is:
% responded S1, confidence rating=3 : 55% of trials
% responded S1, confidence rating=2 : 20% of trials
% responded S1, confidence rating=1 : 15% of trials
% responded S2, confidence rating=1 : 5% of trials
% responded S2, confidence rating=2 : 3% of trials
% responded S2, confidence rating=3 : 2% of trials
%
% And if predicted.S2 = [0.015 0.045 0.09 0.17 0.22 0.46], then when S2
% stimulus was presented, the model prediction is:
% responded S1, confidence rating=3 : 1.5% of trials
% responded S1, confidence rating=2 : 4.5% of trials
% responded S1, confidence rating=1 : 9% of trials
% responded S2, confidence rating=1 : 17% of trials
% responded S2, confidence rating=2 : 22% of trials
% responded S2, confidence rating=3 : 46% of trials
%
% * w
% w = 1 when any warning message is output. w = 0 when there is no warning
% message.
%
% * d
% Estimated value of the parameter d' in Type I signal detection theory.
%
% * C
% Estimated value of the parameter C in Type I signal detection theory.

tic;

w = 0;

nratings = length(nR_S1)/2;

if nratings < 3
    error('BIM can only be applied to a confidence rating scale with no less than 3 points')
end

if length(nR_S1) ~= length(nR_S2)
    error('nR_S1 and nR_S2 must have the same length')
end

% turn off the warning for particleswarm
warning('off','globaloptim:particleswarm:initialSwarmLength');

%% calculate Type I d' and C

HR = sum(nR_S2(nratings+1:end))/sum(nR_S2);
FAR = sum(nR_S1(nratings+1:end))/sum(nR_S1);

if HR>0.99
    HR=0.99;
elseif HR<0.01
    HR=0.01;
end

if FAR>0.99
    FAR=0.99;
elseif FAR<0.01
    FAR=0.01;
end

d = norminv(HR) - norminv(FAR);
C = (-0.5) * (norminv(HR) + norminv(FAR));

%% warning

if sum(nR_S1(1:nratings)) == 0
    warning('There is no S1 response in trials with S1 stimuli. Estimation of Mconf for this condition is inaccurate.')
    w = 1;
end

if sum(nR_S1(nratings+1:end)) == 0
    warning('There is no S2 response in trials with S1 stimuli. Estimation of Mconf for this condition is inaccurate.')
    w = 1;
end

if sum(nR_S2(1:nratings)) == 0
    warning('There is no S1 response in trials with S2 stimuli. Estimation of Mconf for this condition is inaccurate.')
    w = 1;
end

if sum(nR_S2(nratings+1:end)) == 0
    warning('There is no S2 response in trials with S2 stimuli. Estimation of Mconf for this condition is inaccurate.')
    w = 1;
end

%% set up initial values
Pexp = 0.5;
Mconf1 = 0.5;
Mconf2 = 0.5;
Mconf3 = 0.5;
Mconf4 = 0.5;
rho = 0;

params = [Pexp Mconf1 Mconf2 Mconf3 Mconf4 rho];

%% fit the model
% settings for fminsearch
options=optimset('TolFun',1e-10);
options=optimset(options,'TolX',1e-10);
options=optimset(options,'MaxFunEvals',10000);
options=optimset(options,'MaxIter',10000);
options=optimset(options,'Display','off');

% settings for particleswarm
options_pso = optimoptions(@particleswarm,'Display','off','InitialSwarm',[]); 
lb = [0 0 0 0 0 -1];
ub = [1 1 1 1 1 1];
options_pso.InitialSwarm = repmat(params,[1000 1]);

% fit the model
params = particleswarm(@(params) bim_error_bins_recog(params,nR_S1,nR_S2,d,C),length(params),lb,ub,options_pso);
params = fminsearch(@(params) bim_error_bins_recog(params,nR_S1,nR_S2,d,C),params,options);

% turn on the warning for particleswarm
warning('on','globaloptim:particleswarm:initialSwarmLength');

%% generate output
[err,predicted] = bim_error_bins_recog(params,nR_S1,nR_S2,d,C);
logL = -err;

toc;